services:
  config-server:
    build:
      context: ./services/config-server
      dockerfile: Dockerfile  # Ensure you point to the correct Dockerfile
    image: hamsaye/config-server:latest
    container_name: hm_config-server
    ports:
      - 8888:8888
    networks:
      - hamsaye-network
    volumes:
      - ./config-server/src/main/resources/configurations:/app/configurations
    environment:
      - SPRING_PROFILES_ACTIVE=native

  discovery-service:
    build:
      context: ./services/discovery
      dockerfile: Dockerfile  # Ensure you point to the correct Dockerfile
    image: hamsaye/discovery-service:latest
    container_name: hm_discovery-service
    ports:
      - 8761:8761
    networks:
      - hamsaye-network
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - config-server

  chat-service:
    build:
      context: ./services/chat
      dockerfile: Dockerfile  # Ensure you point to the correct Dockerfile
    image: hamsaye/chat-service:latest
    container_name: hm_chat-service
    ports:
      - 8057:8057
    networks:
      - hamsaye-network
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - discovery-service
      - mongodb
      - kafka

  user-service:
    build:
      context: ./services/user
      dockerfile: Dockerfile  # Ensure you point to the correct Dockerfile
    image: hamsaye/user-service:latest
    container_name: hm_user-service
    ports:
      - 8056:8056
    networks:
      - hamsaye-network
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - discovery-service
      - postgres
      - kafka

  postgres:
    container_name: hm_pg_sql
    image: postgres
    environment:
      POSTGRES_USER: pouria
      POSTGRES_PASSWORD: hamsaye1g8S9QJsp61wD53L4nW9d5mou879cSQpD7e38BDB0LwLesB3Rog5eWzU1mp4BEY7
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5433:5432
    networks:
      - hamsaye-network
    restart: unless-stopped

  pgadmin:
    container_name: hm_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - 5050:80
    networks:
      - hamsaye-network
    depends_on:
      postgres:
        condition: service_started
    restart: unless-stopped

  mongodb:
    container_name: hm_mongo
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=pouria
      - MONGO_INITDB_ROOT_PASSWORD=hamsaye1g8S9QJsp61wD53L4nW9d5mou879cSQpD7e38BDB0LwLesB3Rog5eWzU1mp4BEY7
    volumes:
      - mongo:/data
    ports:
      - 27017:27017
    networks:
      - hamsaye-network
    restart: unless-stopped

  mongo-express:
    container_name: hm_mongo_express
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=pouria
      - ME_CONFIG_MONGODB_ADMINPASSWORD=hamsaye1g8S9QJsp61wD53L4nW9d5mou879cSQpD7e38BDB0LwLesB3Rog5eWzU1mp4BEY7
      - ME_CONFIG_MONGODB_SERVER=mongodb
    ports:
      - 8081:8081
    networks:
      - hamsaye-network
    depends_on:
      mongodb:
        condition: service_started
    restart: always

  zookeeper:
    container_name: hm_zookeeper
    image: confluentinc/cp-zookeeper:7.4.4
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - "zookeeper_data:/bitnami"
    ports:
      - 22181:2181
    networks:
      - hamsaye-network
    restart: unless-stopped

  kafka:
    container_name: hm_kafka
    image: confluentinc/cp-kafka:7.4.4
    volumes:
      - "kafka_data:/bitnami"
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CLIENT_USERS: user
      KAFKA_CLIENT_PASSWORDS: password
      KAFKA_CONTROLLER_USER: user
      KAFKA_CONTROLLER_PASSWORD: password
    networks:
      - hamsaye-network
    depends_on:
      zookeeper:
        condition: service_started
    restart: unless-stopped

networks:
  hamsaye-network:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  mongo: {}
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local