
PGSQL_SERVICE_HOST: localhost
PGSQL_SERVICE_PORT: 5432
PGSQL_SERVICE_NAME: db_hamsaye_test

spring:
  datasource:
    url: jdbc:postgresql://${PGSQL_SERVICE_HOST}:${PGSQL_SERVICE_PORT}/${PGSQL_SERVICE_NAME}
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 13791379259

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true

